CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_no VARCHAR2(64) NOT NULL UNIQUE,
    name VARCHAR2(128) NOT NULL,
    phone VARCHAR2(32),
    email VARCHAR2(128),
    status VARCHAR2(32) DEFAULT 'active' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
COMMENT ON TABLE customers IS '客户表';
COMMENT ON COLUMN customers.id IS '客户主键';
COMMENT ON COLUMN customers.customer_no IS '客户编号';
COMMENT ON COLUMN customers.name IS '客户名称';
COMMENT ON COLUMN customers.phone IS '联系电话';
COMMENT ON COLUMN customers.email IS '电子邮箱';
COMMENT ON COLUMN customers.status IS '客户状态';
COMMENT ON COLUMN customers.created_at IS '创建时间';

CREATE TABLE product_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER,
    name VARCHAR2(128) NOT NULL,
    sort_order NUMBER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE product_categories IS '商品分类表';
COMMENT ON COLUMN product_categories.id IS '分类主键';
COMMENT ON COLUMN product_categories.parent_id IS '父分类 ID';
COMMENT ON COLUMN product_categories.name IS '分类名称';
COMMENT ON COLUMN product_categories.sort_order IS '展示排序';

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER NOT NULL,
    sku VARCHAR2(64) NOT NULL UNIQUE,
    name VARCHAR2(160) NOT NULL,
    price NUMBER(12,2) NOT NULL,
    stock_qty NUMBER DEFAULT 0 NOT NULL,
    status VARCHAR2(32) DEFAULT 'on_sale' NOT NULL
);
COMMENT ON TABLE products IS '商品表';
COMMENT ON COLUMN products.id IS '商品主键';
COMMENT ON COLUMN products.category_id IS '所属分类 ID';
COMMENT ON COLUMN products.sku IS '商品 SKU';
COMMENT ON COLUMN products.name IS '商品名称';
COMMENT ON COLUMN products.price IS '销售价格';
COMMENT ON COLUMN products.stock_qty IS '库存数量';
COMMENT ON COLUMN products.status IS '商品状态';

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR2(64) NOT NULL UNIQUE,
    customer_id NUMBER NOT NULL,
    total_amount NUMBER(12,2) NOT NULL,
    order_status VARCHAR2(32) NOT NULL,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
COMMENT ON TABLE orders IS '订单表';
COMMENT ON COLUMN orders.id IS '订单主键';
COMMENT ON COLUMN orders.order_no IS '订单编号';
COMMENT ON COLUMN orders.customer_id IS '下单客户 ID';
COMMENT ON COLUMN orders.total_amount IS '订单总金额';
COMMENT ON COLUMN orders.order_status IS '订单状态';
COMMENT ON COLUMN orders.ordered_at IS '下单时间';

CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    line_amount NUMBER(12,2) NOT NULL
);
COMMENT ON TABLE order_items IS '订单明细表';
COMMENT ON COLUMN order_items.id IS '订单明细主键';
COMMENT ON COLUMN order_items.order_id IS '订单 ID';
COMMENT ON COLUMN order_items.product_id IS '商品 ID';
COMMENT ON COLUMN order_items.quantity IS '购买数量';
COMMENT ON COLUMN order_items.unit_price IS '成交单价';
COMMENT ON COLUMN order_items.line_amount IS '明细金额';

CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no VARCHAR2(64) NOT NULL UNIQUE,
    order_id NUMBER NOT NULL,
    pay_channel VARCHAR2(32) NOT NULL,
    pay_amount NUMBER(12,2) NOT NULL,
    pay_status VARCHAR2(32) NOT NULL,
    paid_at TIMESTAMP
);
COMMENT ON TABLE payments IS '支付记录表';
COMMENT ON COLUMN payments.id IS '支付主键';
COMMENT ON COLUMN payments.payment_no IS '支付流水号';
COMMENT ON COLUMN payments.order_id IS '订单 ID';
COMMENT ON COLUMN payments.pay_channel IS '支付渠道';
COMMENT ON COLUMN payments.pay_amount IS '支付金额';
COMMENT ON COLUMN payments.pay_status IS '支付状态';
COMMENT ON COLUMN payments.paid_at IS '支付完成时间';
